=== ptorbett/ptorbett.github.io/xml/Classes.dtd
<!ELEMENT Classes ( Course+ )>

<!ELEMENT Course ( Date, Name, Title, Units, Description,
 Prerequisites*, Corequisites*, Instructors )>
<!ATTLIST Course id ID #REQUIRED>

<!ELEMENT Date ( Quarter, Year )>

<!ELEMENT Quarter ( #PCDATA )>

<!ELEMENT Year ( #PCDATA )>

<!ELEMENT Name ( Department, Number )>

<!ELEMENT Department ( #PCDATA )>

<!ELEMENT Number ( #PCDATA )>

<!ELEMENT Units (#PCDATA )>

<!ELEMENT Title ( #PCDATA )>

<!ELEMENT Description ( #PCDATA )>

<!ELEMENT Notes #PCDATA?>

<!ELEMENT Prerequisites Prereq*>

<!ELEMENT Prereq Name>

<!ELEMENT Corequisites Coreq+>

<!ELEMENT Coreq Name>

<!ELEMENT Instructors (Professor+|Lecturer+)>

<!ELEMENT Professor ( First_Name, Middle_Initial?, Last_Name )>

<!ELEMENT Lecturer ( First_Name, Middle_Initial?, Last_Name )>

<!ELEMENT First_Name ( #PCDATA )>

<!ELEMENT Middle_Initial ( #PCDATA )>

<!ELEMENT Last_Name ( #PCDATA )>

=== ptorbett/ptorbett.github.io/xml/Classes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Classes SYSTEM "Classes.dtd">
<?xml-stylesheet type="text/xsl" href="Classes.xsl"?>
<Classes>
  <Course id="CSE131">
    <Date>
      <Quarter>Winter</Quarter>
      <Year>2013</Year>
    </Date>
    <Name>
      <Department>CSE</Department>
      <Number>131</Number>
    </Name>
    <Title>Compiler Construction</Title>
    <Units>4</Units>
    <Description>
      Introduction to the compilation of programming languages, practice of
      lexical and syntactic analysis, symbol tables, syntax-directed
      translation, type checking, code generation, optimization,
      interpretation, and compiler structure.
    </Description>
    <Instructors>
      <Lecturer>
        <First_Name>
          Rick
        </First_Name>
        <Last_Name>
          Ord
        </Last_Name>
      </Lecturer>
    </Instructors>
  </Course>
  <Course id="LTWR8B">
    <Date>
      <Quarter>Winter</Quarter>
      <Year>2013</Year>
    </Date>
    <Name>
      <Department>LTWR</Department>
      <Number>8B</Number>
    </Name>
    <Title>Writing Poetry</Title>
    <Units>4</Units>
    <Description>
      Study and practice of poetry as artistic and communal expression.
      Techniques of composition (traditional forms, avant garde techniques,
      dramatic monologue, performance poetry, and new genre) studied through
      written and spoken examples of poetry. Writing exercises accompany
      reading assignments. 
    </Description>
    <Instructors>
      <Lecturer>
        <First_Name>
          Rae
        </First_Name>
        <Last_Name>
          Armantrout
        </Last_Name>
      </Lecturer>
    </Instructors>
  </Course>
  <Course id="TDAC1">
    <Date>
      <Quarter>Winter</Quarter>
      <Year>2013</Year>
    </Date>
    <Name>
      <Department>TDAC</Department>
      <Number>1</Number>
    </Name>
    <Title>Introduction to Acting</Title>
    <Units>4</Units>
    <Description>
      A beginning course in the fundamentals of acting: establishing a working
      vocabulary and acquiring the basic skills of the acting process. Through
      exercises, compositions, and improvisations, the student actor explores
      the imagination as the actorâ€™s primary resource, and the basic approach
      to text through action.
    </Description>
    <Instructors>
      <Lecturer>
        <First_Name>
          Chaz
        </First_Name>
        <Last_Name>
          Hodges
        </Last_Name>
      </Lecturer>
    </Instructors>
  </Course>
  <Course id="HISC104">
    <Date>
      <Quarter>Fall</Quarter>
      <Year>2012</Year>
    </Date>
    <Name>
      <Department>HISC</Department>
      <Number>104</Number>
    </Name>
    <Title>History of Popular Science</Title>
    <Units>4</Units>
    <Description>
      Historical aspects of the popularization of science. The changing
      relation between expert science and popular understanding. The reciprocal
      impact of scientific discoveries and theories, and popular conceptions of
      the natural world.
    </Description>
    <Instructors>
      <Professor>
        <First_Name>
          William
        </First_Name>
        <Last_Name>
          Clark
        </Last_Name>
      </Professor>
    </Instructors>
  </Course>
  <Course id="CSE120">
    <Date>
      <Quarter>Fall</Quarter>
      <Year>2012</Year>
    </Date>
    <Name>
      <Department>CSE</Department>
      <Number>120</Number>
    </Name>
    <Title>Principles of Computer Operating Systems</Title>
    <Units>4</Units>
    <Description>
      This course introduces the basic concepts used to structure computer
      operating systems. Examples of notions introduced and discussed are batch
      processing, multiprogramming, input/output, pooling, interrupt handling,
      processes, descriptors, process synchronization, interprocess
      communication, memory management, virtual memory, caching, buffers,
      naming, files, interactive command interpreters, and processor
      scheduling.
    </Description>
    <Instructors>
      <Professor>
        <First_Name>
          Joseph
        </First_Name>
        <Last_Name>
          Pasquale
        </Last_Name>
      </Professor>
    </Instructors>
  </Course>
  <Course id="CSE101">
    <Date>
      <Quarter>Fall</Quarter>
      <Year>2012</Year>
    </Date>
    <Name>
      <Department>CSE</Department>
      <Number>101</Number>
    </Name>
    <Title>Design and Analysis of Algorithms</Title>
    <Units>4</Units>
    <Description>
      Design and analysis of efficient algorithms with emphasis of non-numerical
      algorithms such as sorting, searching, pattern matching, and graph and
      network algorithms. Measuring complexity of algorithms, time and storage.
      NP-complete problems.
      Algorithmic problems arise in almost every area of computer science. This
      course exposes students to a variety of algorithms for problems from
      various domains. Particular emphasis is on the most basic problems, those
      that arise in many different applications, such as sorting, graph search,
      or finding the minimum spanning tree. Students should learn how the speed
      of algorithms greatly impact their utility. They should learn elementary
      mathematical techniques to analyze algorithms for correctness, time
      complexity, and memory use. They should become familiar with the most
      efficient algorithms for the basic problems. They should learn the most
      useful methods for designing efficient algorithms, and know how to apply
      them to new problems.
    </Description>
    <Instructors>
      <Professor>
        <First_Name>
          Sanjoy
        </First_Name>
        <Last_Name>
          Dasgupta
        </Last_Name>
      </Professor>
    </Instructors>
  </Course>
  <Course id="CSE90">
    <Date>
      <Quarter>Fall</Quarter>
      <Year>2012</Year>
    </Date>
    <Name>
      <Department>CSE</Department>
      <Number>90</Number>
    </Name>
    <Title>Introduction to Advanced Tutor Training</Title>
    <Units>2</Units>
    <Description>
      Seminar that meets once a week for one hour.
    </Description>
    <Instructors>
      <Professor>
        <First_Name>
          Gary
        </First_Name>
        <Last_Name>
          Gillespie
        </Last_Name>
      </Professor>
    </Instructors>
  </Course>
  <Course id="PHIL13">
    <Date>
      <Quarter>Spring</Quarter>
      <Year>2012</Year>
    </Date>
    <Name>
      <Department>PHIL</Department>
      <Number>13</Number>
    </Name>
    <Title>Intro to Philosophy: Ethics</Title>
    <Units>4</Units>
    <Description>
      An inquiry into the nature of morality and its role in personal or social
      life by way of classical and/or contemporary works in ethics.
    </Description>
    <Instructors>
      <Professor>
        <First_Name>
          Erick
        </First_Name>
        <Last_Name>
          Ramirez
        </Last_Name>
      </Professor>
    </Instructors>
  </Course>
  <Course id="HILD7C">
    <Date>
      <Quarter>Spring</Quarter>
      <Year>2012</Year>
    </Date>
    <Name>
      <Department>HILD</Department>
      <Number>7C</Number>
    </Name>
    <Title>Race and Ethnicity in American History</Title>
    <Units>4</Units>
    <Description>
      A lecture-discussion course on the comparative ethnic history of the
      United States. Of central concern will be the Mexican-American, race,
      oppression, mass migrations, ethnicity, city life in industrial America,
      and power and protest in modern America.
    </Description>
    <Instructors>
      <Professor>
        <First_Name>
          David
        </First_Name>
        <Last_Name>
          Gutierrez
        </Last_Name>
      </Professor>
    </Instructors>
  </Course>
  <Course id="CSE130">
    <Date>
      <Quarter>Spring</Quarter>
      <Year>2012</Year>
    </Date>
    <Name>
      <Department>CSE</Department>
      <Number>130</Number>
    </Name>
    <Title>Programming Languages: Principles and Paradigms</Title>
    <Units>4</Units>
    <Description>
      Introduction to programming languages and paradigms, the components that
      comprise them, and the principles of language design, all through the
      analysis and comparison of a variety of languages (e.g., Pascal, Ada,
      C++, PROLOG, ML). Will involve programming in most languages studied.
    </Description>
    <Instructors>
      <Professor>
        <First_Name>
          Ranjit
        </First_Name>
        <Last_Name>
          Jhala
        </Last_Name>
      </Professor>
    </Instructors>
  </Course>
  <Course id="CSE110">
    <Date>
      <Quarter>Spring</Quarter>
      <Year>2012</Year>
    </Date>
    <Name>
      <Department>CSE</Department>
      <Number>110</Number>
    </Name>
    <Title>Software Engineering</Title>
    <Units>4</Units>
    <Description>
      Introduction to software development and engineering methods, including
      specification, design, implementation, testing, and process. an emphasis
      on team development, agile methods, and use of tools as IDE's, version
      control, and test harnesses.
    </Description>
    <Instructors>
      <Professor>
        <First_Name>
          Gary
        </First_Name>
        <Last_Name>
          Gillespie
        </Last_Name>
      </Professor>
    </Instructors>
  </Course>
  <Course id="CSE105">
    <Date>
      <Quarter>Winter</Quarter>
      <Year>2012</Year>
    </Date>
    <Name>
      <Department>CSE</Department>
      <Number>105</Number>
    </Name>
    <Title>Theory of Computability</Title>
    <Units>4</Units>
    <Description >An introduction to the mathematical theory of computability. Formal languages. Finite automata and regular expression. Push-down automata and context-free languages. Computable or recursive functions: Turing machines, the halting problem.</Description>
    <Instructors>
      <Professor>
        <First_Name>
          Hovav
